export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST'
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS'
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL'

export const PROFILE_EXPERIENCE_DELETE = 'PROFILE_EXPERIENCE_DELETE'
export const PROFILE_EDUCATION_DELETE = 'PROFILE_EDUCATION_DELETE'

export const PROFILES_GET = 'PROFILES_GET'

export const GET_REPOS = 'GET_REPOS'
